version: "3.8"
services:
  ecomm:
    image: keicee32/learning-app-ecommerce:v1
    ports:
      - 80:80
    env_file:
      - ./.env
    networks:
      - app

  db:
    image: mariadb
    env_file:
      - ./.env
    networks:
      - app

networks:
  app:
    driver: bridge
